version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-sam-cli-sourcebucket-us-east-1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset=false