
name: AWS SAM deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Versions
        run: |
          echo 'SAM: $(sam --version)'
          echo 'Yarn: $(yarn --version)'
          echo 'Node: $(node --version)'

      - name: Install dependencies
        run: yarn

      - name: Transpile JS
        run: |
          NODE_ENV=production yarn build
          cd build/dependencies/nodejs && yarn
      
      - name: Generate resources
        run: |
          mkdir build/dependencies/nodejs/resources
          echo '${{ secrets.JWT_PRIVATE_KEY }}' > build/dependencies/nodejs/resources/jwt.key
          echo '${{ secrets.JWT_PUBLIC_KEY }}' > build/dependencies/nodejs/resources/jwt.pub
          echo '${{ secrets.FIREBASE_ADMIN_DEV }}' > build/dependencies/nodejs/resources/firebase_admin.json

      - name: Sam build & deploy
        run: |
          sam build
          sam deploy --stack-name sls-proj-pronetplat-aa-dev \
            --s3-prefix sls-proj-pronetplat-aa-dev \
            --parameter-overrides Stage=dev \
            --tags what="sls-proj-pronetplat-aa" stage="dev"