# This is a basic workflow to help you get started with Actions

name: AWS SAM deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: pahud/aws-sam-cli:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: sam build
        run: sam build

      - name: sam deploy
        run: sam deploy --stack-name proj-pronetplat-aa \
          --s3-prefix proj-pronetplat-aa \
          --s3-prefix proj-pronetplat-aa \
          --parameter-overrides Stage=dev